import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav.jsx"
import {
  Bodoni_Moda,
  Bebas_Neue,
  Archivo_Black,
  Monoton,
  Plaster,
  Protest_Guerrilla,
  Sonsie_One,
} from "next/font/google";

// Define each font with weights you want
const bodoni = Bodoni_Moda({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // adjust as needed
  variable: "--font-bodoni",
});

const bebas = Bebas_Neue({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-bebas",
});

const archivo = Archivo_Black({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-archivo",
});

const monoton = Monoton({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-monoton",
});

const plaster = Plaster({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-plaster",
});

const protest = Protest_Guerrilla({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-protest",
});

const sonsie = Sonsie_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-sonsie",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${bodoni.variable} ${bebas.variable} ${archivo.variable} ${monoton.variable} ${plaster.variable} ${protest.variable} ${sonsie.variable}`}>
      <head>
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiasedmax-w-screen overflow-x-hidden `}
      >
        <Nav/>
        {children}
      </body>
    </html>
  );
}
